name: Docker Image CI

on:
  push:
    branches:
      - master
      
env:
  DEP_PATH: requirements.txt
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
            docker login -u $DOCKER_USERNAME - p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag comp7940/chatbot:latest

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USERNAME}}/chatbot
