name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEP_PATH: requirements.txt
  
jobs:
  build:
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
      MYSQL_HOST: ${{secrets.MYSQL_HOST}}
      MYSQL_USER: ${{secrets.MYSQL_USER}}
      MYSQL_PASS: ${{secrets.MYSQL_PASS}}
      MYSQL_DTBS: ${{secrets.MYSQL_DTBS}}
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Deploy
        run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

      - name: Build the Docker image
        run: docker build --build-arg ACCESS_TOKEN=$ACCESS_TOKEN --build-arg MYSQL_HOST=$MYSQL_HOST --build-arg MYSQL_USER=$MYSQL_USER --build-arg MYSQL_PASS=$MYSQL_PASS --build-arg MYSQL_DTBS=$MYSQL_DTBS --no-cache . -t ${{secrets.DOCKER_USERNAME}}/chatbot:latest

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USERNAME}}/chatbot
